var num1 = prompt("Enter first number: ");
var num2 = prompt("Enter second number: ");
num1 = parseInt(num1, 10);
num2 = parseInt(num2, 10);
var sum, sub, mul;
sum = num1 + num2;
sub = num1 - num2;
mul = num1 * num2;
div = num1 / num2;
mod = num1 % num2;
document.write("Addition = " + sum + "<br/>");
document.write("Subtraction = " + sub + "<br/>");
document.write("Multiplication = " + mul + "<br/>");
document.write("Divition = " + div + "<br/>");
document.write("Modulas = " + mod + "<br/>");